require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
