
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: selfhouse_development

test:
  <<: *default
  database: selfhouse_test

production:
  <<: *default
  database: selfhouse_production
  username: selfhouse
  password: <%= ENV['SELFHOUSE_DATABASE_PASSWORD'] %>
